#!/usr/bin/env zsh

() {
  emulate -L zsh -o extended_glob
  [[ $_zconf_word_prefix != *('$'|'\') ]] || return
  if [[ $_zconf_word_prefix == *[A-Z]* ]]; then
    [[ -z ${(@)*:#$_zconf_word_prefix*} ]] || return
  else
    [[ -z ${(@)*:#(#i)$_zconf_word_prefix*} ]] || return
  fi
} "$@" || _zconf_word_prefix=
_zconf_word_prefix=${_zconf_word_prefix// /\\ }
