#!/usr/bin/env zsh

eval "$_zconf_opt"

local file=$ZCONF_PACKAGE_DIR/forgit.plugin.zsh
[[ -e $file ]] || return 0

local code
code=$(<$file) || return

local orig="
set | awk -F '=' '{ print \$1 }' | grep FORGIT_ | while read -r var; do
    if ! export | grep -q \"\\(^\$var=\\|^export \$var=\\)\"; then
"
local sub='
for var in "${(@)parameters[(I)FORGIT_*]}"; do
    if [[ ${parameters[$var]} != *export* ]]; then
'
print -r -- ${code/$orig/$sub} >$file
