#!/usr/bin/env zsh

local x
builtin printf -v x "$@"

(( _zconf_can_save_restore_screen )) && x+=$'\ePtmux;'${x//$'\e'/$'\e\e'}$'\e\\'

if [[ -t 1 ]]; then
  print -rn -- "$x"
elif [[ -v _zconf_tty_fd ]]; then
  print -rnu $_zconf_tty_fd -- "$x"
fi
