#!/usr/bin/env zsh

eval "$_zconf_opt"

if [[ -n $_ZCONF_TMUX ]]; then
  local pane
  pane="$(TMUX=$_ZCONF_TMUX TMUX_PANE=$_ZCONF_TMUX_PANE $_ZCONF_TMUX_CMD capture-pane -p -e && print -n x)" || return
  typeset -g _zconf_saved_screen=$'\e[0m\e[H'${${pane//$'\n'/$'\e[49m\e[K\r\n'}%$'\r\nx'}
elif [[ -n $ZCONF_SSH && -n $_ZCONF_SSH_MARKER && -v _zconf_tty_fd ]]; then
  printf '\001zconf.%s%s' "$_ZCONF_SSH_MARKER" 'save-screen     ' >&$_zconf_tty_fd
else
  return 1
fi
