#!/usr/bin/env zsh

eval "$_zconf_opt"
-zconf-check-core-params || return

if (( ARGC )); then
  print -Pru2 -- '%F{3}zconf%f: unexpected %F{1}update%f argument'
  return '_zconf_err()'
fi

if (( _zconf_dangerous_root )); then
  print -Pru2 -- "%F{3}zconf%f: refusing to %Bupdate%b as %F{1}root%f"
  return 1
fi

local old=$ZCONF.old.$$
local new=$ZCONF.new.$$

{
  zf_rm -rf -- $old $new   || return
  zf_mkdir -p -- $new      || return
  print -n >$new/.updating || return

  ZCONF_UPDATING=$ZCONF ZCONF=$new </dev/null >/dev/null $_zconf_exe -ic '
    (( $? )) && "exit" "1"
    "builtin" "emulate" "zsh" "-o" "no_aliases"
    [[ $ZCONF == '${(q)new}' ]] || exit 0
    print -n >$ZCONF/tmp/update-successful' || return

  if [[ ! -e $new/tmp/update-successful ]]; then
    local home=~
    local zdotdir=${${${(q)ZDOTDIR}/#${(q)home}/'~'}//\%/%%}
    local zconf=${${${(q)ZCONF}/#${(q)home}/'~'}//\%/%%}
    print -Pru2 -- '%F{3}zconf%f: %B$ZCONF%b %F{1}does not propagate%f through %U.zshrc%u'
    print -Pru2 -- ''
    print -Pru2 -- 'Change %U'$zdotdir'/.zshrc%u to keep %BZCONF%b intact if already set.'
    print -Pru2 -- ''
    print -Pru2 -- 'For example:'
    print -Pru2 -- ''
    print -Pru2 -- '  %F{2}:%f %F{3}"${ZCONF:=${XDG_CACHE_HOME:-$HOME/.cache}/zsh}"%f'
    print -Pru2 -- ''
    print -Pru2 -- 'Note: The leading colon (%F{2}:%f) is necessary.'
    return 1
  fi

  zf_rm -- $new/tmp/update-successful                || return
  zf_rm -- $new/.updating                            || return
  -zconf-mv $ZCONF $old 2>/dev/null || zf_rm -rf -- $ZCONF || return
  if [[ -e $ZCONF ]]; then
    local home=~
    local zconf=${${${(q)ZCONF}/#${(q)home}/'~'}//\%/%%}
    print -Pru2 -- '%F{3}zconf%f: %F{1}cannot delete %U'$zconf'%u%f'
    print -Pru2 -- ''
    print -Pru2 -- 'This might help:'
    print -Pru2 -- ''
    print -Pru2 -- '  %F{2}%Ucommand%u %Usudo%u rm%f -rf -- %U'$zconf'%u && %U%F{2}exec%u zsh%f'
    print -Pru2 -- ''
    print -Pru2 -- '%F{3}zconf%f: attempting to recover'
    if [[ ! -e $ZCONF/stickycache ]]; then
      command cp -r -- $new/stickycache $ZCONF/stickycache || true
    fi
    if [[ -o zle ]]; then
      exec -- $_zconf_exe -i || return
    else
      exec -- $_zconf_exe -i --no-zle || return
    fi
  fi
  -zconf-mv $new $ZCONF || return
} always {
  if (( $? )); then
    -zconf-error-command update
  fi
  zf_rm -rf -- $old $new || return
}

print -Pru2 -- "%F{3}zconf%f: %Bupdate successful%b"
print -Pru2 -- "%F{3}zconf%f: restarting %F{2}zsh%f"
if [[ -o zle ]]; then
  exec -- $_zconf_exe -i || return
else
  exec -- $_zconf_exe -i --no-zle || return
fi
