#!/usr/bin/env zsh

if (( ${+_zconf_redraw_fd} )); then
  zle -F "$_zconf_redraw_fd"
  exec {_zconf_redraw_fd}>&-
  unset _zconf_redraw_fd
fi

if [[ -v region_highlight &&
      ( ${LASTWIDGET-} != accept-line || ${WIDGET-} != zle-line-pre-redraw ) ]]; then
  _zsh_highlight
  -zconf-autosuggest-fetch
fi
