#!/usr/bin/env zsh

[[ -v _zconf_tty_fd ]] || return

builtin echoti civis >&$_zconf_tty_fd
builtin print -rnu $_zconf_tty_fd -- $'\e[H\e[2J'
builtin zle .reset-prompt
builtin zle -R
builtin print -rnu $_zconf_tty_fd -- $'\e[3J'
-zconf-cursor-show
