#!/usr/bin/env zsh

[[ -v _zconf_tty_fd ]] || return

autoload +X -Uz -- -zconf-present-files -zconf-cursor-show -zconf-find -zconf-fzf

local -i dot_glob list_types
[[ -o dot_glob   ]] && dot_glob=1
[[ -o list_types ]] && list_types=1

-zconf-set-list-colors :complete:cd:: $list_types
local -i list_colors=$((!$?))

{
  -zconf-cursor-hide

  local -i first=1
  while true; do
    local -i redraw=0 again=0
    () {
      eval "$_zconf_opt"
      if (( dot_glob )); then
        local dirs=(*(-/DN))
      else
        local dirs=(*(-/N))
      fi
      local non_empty=(${^${dirs}}/*(D-/Y1N:h:t))

      if (( first )); then
        first=0
      elif (( ! $#dirs )); then
        return 0
      fi

      {
        -zconf-show-dots ''

        local -i pct=60
        (( _zconf_can_save_restore_screen )) && pct=100

        local -i height=$(( ! $#non_empty && 100 * ($#dirs + 4) < pct * LINES ? $#dirs + 4 : pct * LINES / 100 ))

        (( height >= 6 )) || (( height = 6 ))
        (( height <= LINES - 1 )) || (( height = LINES - 1 ))

        local opts=(
          --color=hl:201,hl+:201
          --with-nth=2
          --delimiter='\000'
          --ansi
          --exact
          --no-mouse
          --tiebreak=length,begin,index
          --no-multi
          --border=horizontal
        )

        () {
          emulate -L zsh
          # Set dot_glob in case the value of find-flags depends on it (via `zstyle -e`).
          # Ideally we should run this with user options.
          (( dot_glob )) && setopt dot_glob
          local -a bin
          zstyle -a :zconf:${WIDGET#zconf-} find-command bin
          if (( ! $#bin )) && (( $+commands[bfs] )); then
            opts+=(--no-sort)
          fi
        }

        local cursor_y cursor_x
        -zconf-get-cursor-pos || return

        if (( _zconf_can_save_restore_screen )); then
          opts+=(--no-clear)
          if { (( height <= cursor_y - 1 )) && zstyle -T :zconf: prompt-at-bottom } ||
             (( cursor_y - 1 > LINES - cursor_y && cursor_y - 1 > 4 )) &&
             { (( height > LINES - cursor_y )) || zstyle -T :zconf: prompt-at-bottom }; then
            (( height <= cursor_y - 1 )) || (( height = cursor_y - 1 ))
            local move=$'\e[0m\e['$((cursor_y-height))';1H'
            opts+=(--layout=default)
          elif (( LINES - cursor_y > 4 )); then
            (( height <= LINES - cursor_y )) || (( height = LINES - cursor_y ))
            local move=$'\e[0m\n\r'
            opts+=(--layout=reverse)
          else
            local -i extra=$((height - LINES + cursor_y))
            print -rnu $_zconf_tty_fd -- ${(pl:$height::\n:)} || return
            (( cursor_y += LINES - cursor_y - height ))
            local move=$'\e[0m\e['$((cursor_y+1))';1H'
            opts+=(--layout=reverse)
          fi
          local _zconf_saved_screen
          -zconf-save-screen || return
        else
          print -u $_zconf_tty_fd || return
          local move=
          opts+=(--layout=reverse)
        fi

        opts+=(--height=$height)

        {
          local choice
          choice=$(
            unsetopt pipe_fail
            exec 2>/dev/null
            {
              print -r -- $sysparams[pid]
              print -rC1 -- $dirs
              -zconf-find $dot_glob 1 $non_empty | command sed -n '/\/.*\// s/^..//p'
            } | {
              local -a pids
              IFS=' ' builtin read -rA pids || exit
              print -r -- $pids $sysparams[pid] || exit
              -zconf-present-files $list_colors $list_types 0
            } | {
              local -a pids
              IFS=' ' builtin read -rA pids || pids=()
              print -rnu $_zconf_tty_fd -- $move
              -zconf-cursor-show
              2>&$_zconf_tty_fd -zconf-fzf $opts
              (( $#pids )) && builtin kill -- $pids
            } always {
              -zconf-cursor-hide
            })
          [[ -n $choice ]] || return
          choice=("${(@f)choice}")
          [[ -n $choice[1] ]] && again=1
          cd -- ${choice[2]%%$'\0'*} 2>/dev/null || return
          redraw=1
        } always {
          if (( _zconf_can_save_restore_screen )); then
            -zconf-restore-screen
            print -rn -- $'\e[0m\e['$cursor_y';'$cursor_x'H'
          else
            builtin echoti cuu 1
            (( cursor_x > 1 )) && builtin echoti cuf $((cursor_x-1))
          fi
        }
      } always {
        zle -R
      }
    } || return
    (( redraw )) && -zconf-redraw-prompt 1
    (( again )) || break
  done
} always {
  -zconf-cursor-show
}
