#!/usr/bin/env zsh

[[ -v _zconf_tty_fd ]] || return

builtin echoti civis >&$_zconf_tty_fd
local -i cursor_x cursor_y
-zconf-get-cursor-pos || cursor_y=0
builtin print -rnu $_zconf_tty_fd -- "${(pl:$((2 * LINES - cursor_y - 1))::\n:)}"
builtin zle -I
builtin zle -R
-zconf-cursor-show
