#!/usr/bin/env zsh
#
# zconf-accept-line is just like accept-line except that it inserts \n when
# accept-line would result in a parse error or PS2.

if -zconf-is-valid-list "$PREBUFFER$BUFFER"; then
  zle accept-line
else
  LBUFFER+=$'\n'
fi
