#!/usr/bin/env zsh

local code=$?
builtin eval "$_zconf_opt"
builtin zle || builtin exit code
typeset -g precmd_functions=(zconf-exit)
if [[ $BUFFER == [[:space:]]# ]]; then
  builtin zle -w accept-line
else
  builtin zle -w send-break
fi
