#!/usr/bin/env zsh

[[ -v _zconf_tty_fd ]] || return

builtin echoti civis >&$_zconf_tty_fd
local -i cursor_x cursor_y
-zconf-get-cursor-pos || cursor_y=0
builtin print -rnu $_zconf_tty_fd -- "${(pl:$((2 * LINES - cursor_y))::\n:)}"$'\e[H\e[2J'
builtin zle .reset-prompt
builtin zle -R
-zconf-cursor-show
