#!/usr/bin/env zsh

local code=$?
builtin zle || builtin exit code
if [[ "$CONTEXT" == start && -z "$BUFFER" ]]; then
  typeset -g precmd_functions=(zconf-eof)
  builtin zle -w accept-line
else
  zle -w delete-char-or-list
fi
