# Personal Zsh configuration file. It is strongly recommended to keep all
# shell customization and configuration (including exported environment
# variables such as PATH) in this file or in files sourced from it.
#
# Documentation: https://github.com/c0mpile/zsh-config/blob/v5/README.md.

# Periodic auto-update on Zsh startup: 'ask' or 'no'.
# You can manually run `zconf update` to update everything.
zstyle ':zconf:' auto-update      'no'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':zconf:' auto-update-days '28'

# Keyboard type: 'mac' or 'pc'.
zstyle ':zconf:bindkey' keyboard  'mac'

# Mark up shell's output with semantic information.
zstyle ':zconf:' term-shell-integration 'yes'

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':zconf:autosuggestions' forward-char 'accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':zconf:fzf-complete' recurse-dirs 'no'

# Enable direnv to automatically source .envrc files.
zstyle ':zconf:direnv'         enable 'no'
# Show "loading" and "unloading" notifications from direnv.
zstyle ':zconf:direnv:success' notify 'yes'

# Enable ('yes') or disable ('no') automatic teleportation of zconf over
# SSH when connecting to these hosts.
zstyle ':zconf:ssh:example-hostname1'   enable 'yes'
zstyle ':zconf:ssh:*.example-hostname2' enable 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':zconf:ssh:*'                   enable 'no'

# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':zconf:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `zconf init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
zconf install ohmyzsh/ohmyzsh || return

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
zconf init || return

# Extend PATH.
path=(~/bin $path)

# Export environment variables.
export GPG_TTY=$TTY

# Source additional local files if they exist.
zconf source ~/.env.zsh

# Use additional Git repositories pulled in with `zconf install`.
#
# This is just an example that you should delete. It does nothing useful.
zconf source ohmyzsh/ohmyzsh/lib/diagnostics.zsh  # source an individual file
zconf load   ohmyzsh/ohmyzsh/plugins/emoji-clock  # load a plugin

# Define key bindings.
zconf bindkey undo Ctrl+/   Shift+Tab  # undo the last command line change
zconf bindkey redo Option+/            # redo the last undone command line change

zconf bindkey zconf-cd-back    Shift+Left   # cd into the previous directory
zconf bindkey zconf-cd-forward Shift+Right  # cd into the next directory
zconf bindkey zconf-cd-up      Shift+Up     # cd into the parent directory
zconf bindkey zconf-cd-down    Shift+Down   # cd into a child directory

# Autoload functions.
autoload -Uz zmv

# Define functions and completions.
function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
compdef _directories md

# Define named directories: ~w <=> Windows home directory on WSL.
[[ -z $zconf_win_home ]] || hash -d w=$zconf_win_home

# Define aliases.
alias tree='tree -a -I .git'

# Add flags to existing aliases.
alias ls="${aliases[ls]:-ls} -A"

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu
